version: '3'

services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: ./Dockerfile
    depends_on:
      - postgres_db
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: ['mosquitto', '-c', '/mosquitto/config/mosquitto.conf']
    ports:
      - 1883:1883
      - 9001:9001

  postgres_db:
    build: 
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: mosquitto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  mqtt_server:
    image: python:3-alpine
    volumes:
      - ./loop.sh:/loop.sh
      - ./mqtt_server:/mqtt_server
    command: ['/bin/sh', '/loop.sh']

  node_client:
    image: node:10-alpine
    volumes:
      - ./loop.sh:/loop.sh
    command: ['/bin/sh', '/loop.sh']

