version: '3'

services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: ./Dockerfile
    depends_on:
      - postgres_db
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  postgres_db:
    build: 
      context: ./postgres
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_DB: mosquitto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  mqtt_server:
    image: python:3-alpine
    volumes:
      - ./loop.sh:/loop.sh
    command: ['/bin/sh', '/loop.sh']

